POST http://localhost:5133/products
Content-Type: application/json

{
    "Title": "Test",
    "Description": "test description",
    "Category": 1,
    "TypeOfMeasurement": 1,
    "Quantity": 1.0,
    "inStock": true,
    "boughOn": "2025-05-01",
    "StorageId": "544944f3-a717-4f78-81d6-1096f2b39da8"
}